### ISSUE TITLE
Improve performance by allowing commands and namespaces to be `require`d dinamically

### ISSUE THREAD

**Issue by vibegui** [vtex/findhelp#5]
`findhelp` should have an API that allows the user to pass in names of modules, so it can lazily require commands and namespaces.

This should immensely improve start-up times for any non-trivial CLI application.

Suggestions on how to do it? I'd like to keep it simple. Maybe a `module` property which has more priority than handler?

@rdumont @tamorim

**Comment by rdumont** [comment]
I was just thinking about this yesterday, because `vtex` startup time is now more than one second. My idea is also in the way of a `module` property, as you suggested. Would it be something along these lines?

### `apps/index.js`

``` js
export default {
  list: {
    description: 'List apps',
    module: './commands'
  }
}
```

### `apps/commands.js`

``` js
export default {
  list: async () => {
    console.log('Hello list')
  }
}
```

**Comment by vibegui** [comment]
Why have the `list` key twice? I'd think it would be more natural/interchangeable with the default API to have the new module behave precisely as if the `{module}` object was _replaced_ by the module. In your example, the child would have `description` and `handler` properties.

**Comment by vibegui** [comment]
@rdumont it dawned on me today that we might fix the performance problem by simply _bundling_ the entire `lib/` with webpack on `prepublish`. What do you think?

**Comment by rdumont** [comment]
Well, we have to test it, but I wouldn't give up on the dynamic modules.

**Comment by tamorim** [comment]
Done on 3793ed7dce042577da7cf1282a982119bddc5cab
